/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iMasterChefSol from "./IMasterChef.sol";
export type { iMasterChefSol };
export type { IAntiDumpGuard } from "./IAntiDumpGuard";
export type { IDarwinLiquidityBundles } from "./IDarwinLiquidityBundles";
export type { IDarwinSwapCallee } from "./IDarwinSwapCallee";
export type { IDarwinSwapERC20 } from "./IDarwinSwapERC20";
export type { IDarwinSwapFactory } from "./IDarwinSwapFactory";
export type { IDarwinSwapLister } from "./IDarwinSwapLister";
export type { IDarwinSwapPair } from "./IDarwinSwapPair";
export type { IDarwinSwapRouter } from "./IDarwinSwapRouter";
export type { IERC20 } from "./IERC20";
export type { ITokenLocker } from "./ITokenLocker";
export type { IWETH } from "./IWETH";
