/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iMasterChefSol from "./IMasterChef.sol";
export { IAntiDumpGuard__factory } from "./IAntiDumpGuard__factory";
export { IDarwinLiquidityBundles__factory } from "./IDarwinLiquidityBundles__factory";
export { IDarwinStaking__factory } from "./IDarwinStaking__factory";
export { IDarwinSwapCallee__factory } from "./IDarwinSwapCallee__factory";
export { IDarwinSwapERC20__factory } from "./IDarwinSwapERC20__factory";
export { IDarwinSwapFactory__factory } from "./IDarwinSwapFactory__factory";
export { IDarwinSwapLister__factory } from "./IDarwinSwapLister__factory";
export { IDarwinSwapPair__factory } from "./IDarwinSwapPair__factory";
export { IDarwinSwapRouter__factory } from "./IDarwinSwapRouter__factory";
export { IERC20__factory } from "./IERC20__factory";
export { ITokenLocker__factory } from "./ITokenLocker__factory";
export { IWETH__factory } from "./IWETH__factory";
